name: Backend CI
on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradle/**'
      - 'gradlew*'
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradle/**'
      - 'gradlew*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Detekt
        run: ./gradlew detekt --no-daemon

      - name: Build backend
        run: ./gradlew build --no-daemon
