name: Visual regression test
on:
  push:
    branches: [main]
    paths:
      - 'frontend/**/*.stories.tsx'
      - 'frontend/**/*.stories.ts'
      - 'frontend/**/*.stories.jsx'
      - 'frontend/**/*.stories.js'
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**/*.stories.tsx'
      - 'frontend/**/*.stories.ts'
      - 'frontend/**/*.stories.jsx'
      - 'frontend/**/*.stories.js'
jobs:
  e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.11.0'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npm exec playwright install --with-deps

      - name: Run tests
        run: npm exec playwright test
        env:
          ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}
